### PR TITLE
A new OSIRIS isntaller script.

### PR DESCRIPTION
**Pull request by alexrudy**
Here is a new, hacked-together version of the OSIRIS pipeline install script. Please try it out and find the bugs!

### CODE REVIEW

**Comment by followthesheep** [comment]
Do we want to put this install script in as part of the 4.0beta? Or should we wait for the next version?

**Comment by alexrudy** [comment]
OK, the script has been modified to work with the bundled ql2 and odrfgui. I didn't see oopgui bundled at this point, so it will still be installed separately, along with the PDF manuals (which might be out of date).

The script does warn the user if the script would overwrite files in the destination directory. This means that running the script to install over old DRS installations is not a problem, but it might change the checked out files in a git users working directory. (Something that they can fix with e.g. a ``git reset --hard HEAD``)

For users that want to try this out without downloading files (i.e. in a git clone), I've added a ``--no-download`` option, which simply uses the files it finds in place. I don't think this script should do anything more intelligent with git clones right now, as the script does nothing more than set up the source files, then run ``make all`` with appropriate environment variables set.

**Comment by followthesheep** [comment]
Can you change the pull request into the release branch instead of develop? That way we can all test the same branch. Thanks!

**Comment by alexrudy** [comment]
@followthesheep done!

**Pull request merged**
