### PR TITLE
Ability to silence setup scripts

### PR DESCRIPTION
**Pull request by alexrudy**
Just set ``OSIRIS_VERBOSE=0`` before running the setup scripts. This is useful when source-ing these scripts in your ``.profile`` and you don't want to see messages every time.

Also added a comment to the README about this.

### CODE REVIEW

**Comment by followthesheep** [comment]
So we need to explain that the user needs to set an additional environment variable for this to work?

**Comment by alexrudy** [comment]
What do you think of the comment in the readme? 

I think it is better to print useful messages by default, especially for new users. Personally, I always dislike sourcing yet another script when I'm not sure what it is doing to my environment. I know this minorly discourages the use of the setup script in your dotfiles but I think it's worth it for the clarity it provides for new users who might not set up the environment properly.

**Comment by followthesheep** [comment]
I think to help new users, we should be more explicit in the readme by
giving the lines they should add to their .cshrc file or .bashrc files. For
example:

set OSIRIS_ROOT /path/to/directory
set OSIRIS_VERBOSE 0
source ${OSIRIS_ROOT}/scripts/osirisSetup.csh

**Comment by alexrudy** [comment]
@followthesheep Agreed & Done.

**Pull request merged**
